language: python
python:
 - 3.6
 - 3.7
before_install:
 - cd backend
before_script:
 - python3 ./scripts/setup_db.py
script:
 - python3 -m unittest discover tests/api
 - python3 -m unittest discover tests/unit
services:
 - postgresql
