matrix:
  include:
  - os:
    - linux
    language: python
    python:
    - 3.7
    before_install:
    - cd backend
    before_script:
    - python3 ./scripts/setup_db.py
    script:
    - python3 -m unittest discover tests/api
    - python3 -m unittest discover tests/unit
    - flake8 .
    - isort --check-only
    - black --check .
    services:
    - postgresql
  - os:
    - linux
    language: dart
    dart:
    - stable
    before_script:
    - cd frontend
    - git clone https://github.com/flutter/flutter.git -b beta
    - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
    - "./flutter/bin/flutter doctor"
    script:
    - flutter test
env:
  secure: IcK7immBC9l7+GhfSAv2hx1GW38koayCkacO7QbTP7GoL9PAGS8rYeyqEPf3pAkZsK2v2fIzzvT14+8pCUKRCTAbMls+rzPznTapTniKqKG7ZtxIgp4QY51NF8EvsNzdXM6DgHUAIqQmNhYBMbpmDOn7G4jEq4XLkJ4/rd6wVEF6Er/Sfa7OuQ0j3hwakiEuwZL0UA6si4ljBobwjw8QjJVc5bW1nVeiq5utxcA/kQHe7xIQf0HOvFjkZoeWFsq0HpI+lXWubrKqzKXnwK3yaiXWU/wtkCdfraQYCQJNxK0BLaduEctvBtCuyOQV9waDFPcSPU9R52Xp0d/BZH/owY22hImOE+c9JQVFWxmueMHyE+9d0J0Kcw6Jkp+KHWyiTH7IlQ/JBZbboY/4tBUGHJM7KIsJcXUhzKJ3SIoZ1kIxRJ8Xu4DAu49pAG2OXsqTAVSBPx/rhs4eFXzu2eJIefYP010Vkuac84MS3ugdYG05+YDCwvvs/I+eErpJsdlSN14kWC5QNldlzhcZCD6DKunBvxsLWwFVjOydiMut3e4OglL6USV0rtB/3LLcDlO5vjbGvH+Mrp3hFMSaCth0gYbp4NfLwG2pUjDtCZYgfe0M0f9KVxHLjELPRjPcmR9NJX807pp+KhUZJpycaSpQzzCxiKLV7n+SjtlKxmPcE5Q=
  global:
  - secure: XR5V+mrXY60Rxq6y7Mr3fUjxxCRqzbGrMm24b273HSr7R+rrQuBA+MSoBs/KQSOZx1QPHv88xwEI7fg+JeP7MgpXfnR03kxc5qNEAQciWzTcfybXrRCmAuYRRXK3Vhy7nPv7+2JDmKHND2ygaWNpNT2zjiT6LPY/Ddd+r1w4z1A2KPofqwHGyx1RDUinABlusVvWdAtE3YcF2ssYfaXswprHBTJZVBzjOuGvG6J7GZhJSUAEk3sEWxEu+dr8laTxL+m5ushRH94pYzYWCFs1mVCCH3wkX9DjfaPTBS36aWqsA5KPgYx+GgPnrfXwzw7ghv8kT1JCtHU0GEgHHzEK3iqBOCNxwtNgragaB/C6/RUYU2TF/RncokKPtcvZrvuxRnrvNHJ5AQawzbl4VhA9Y09Av5xp93XSdG9okyZSKtfaKyqnGdBabMTbhgv7hDANJSh/YwhzHYpdjvPLxc/inMuH3IEJYXc9J9y2CLhZ5jGtFcYIhucFTxWlYcGVthG3IX0xtVRQOuNudtAC9imFRcfYOK4bfqRjydKrbZDRmIumS6NLG2eHkQRjtGk6jBVBF3Dh0aFm2g0kcDy6rn9wVDS3Y6zlviSlGBfGn8lNryMHix47eZdG9XeOxsjD58CO8b9Z4ax/9tTxe7qw4si9Zo+SxSF1x9/JtsjEOq4BqRM=
  - secure: FDCHYwWcmCYPkAyWd42+hQ7FJTlaoZZ94Bi9kIWKjpxDKnYtN43qrOMkr7edDPS+pcaJlCHqCg3yzl0j5pOqLmu4xNBaZt6AE034TVKADMVV/GyCttKEG2SatIJZMEakNlzXHi5zZFsaqQ8FG/W4tTRl0hLN9H3vOGwdgx5CeVqRvlJHoQFr2pvBroq7qOFuYhMdEQA5C774NEpioCiIIrWNlYe3uNoLMvwEB5tWAZvNw5AICtz9qY9DGvodwWXcygxVPI5s15bteXGqIZgU+n3UA2WvKrtZ7rmKH2LAgDo1CSgxLGRYZLNlCjjtINVJ1Rp+D0S0owGfeHFmxWt+fn3rgHQfN53B3lrKxt3zlPfSA2MHqtdSmNhvqqpv+tMF40QOU0LZbNIDvReHydUKrWy7SI+V5mfN+o5FVp92zyvSzZAXzDrt8zrUb59Iu43F8U5cBaeIlN43uEjMS/ufuOOSEVOSIsQEOaTbQKrkxsCn7+z8VSaJLU/HtMtAtUnTLZh+N37iM0g2/B9rtEWNc75npcz+7ib2qnX6RzdvEX+mfdFe4deDx00VQ+onZVMjxpy3nCW6fnxZHyo9LMbPEmTQDP4Rmv8EwwmpSVeFfWiK1EbK1tlTMYRveDrLkVKLvABNI6qzQ6QuqovrZsR6zMtVnXN9WiX61qJgSVFQxN8=
